# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cauteum.control.v1 import console_pb2 as cauteum_dot_control_dot_v1_dot_console__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cauteum/control/v1/console_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConsoleServiceStub(object):
    """ConsoleService provides safe, user-facing gateway summary methods.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetViewer = channel.unary_unary(
                '/cauteum.control.v1.ConsoleService/GetViewer',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetViewerRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetViewerResponse.FromString,
                _registered_method=True)
        self.GetConsoleCapabilities = channel.unary_unary(
                '/cauteum.control.v1.ConsoleService/GetConsoleCapabilities',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetConsoleCapabilitiesRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetConsoleCapabilitiesResponse.FromString,
                _registered_method=True)
        self.GetOverview = channel.unary_unary(
                '/cauteum.control.v1.ConsoleService/GetOverview',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetOverviewRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetOverviewResponse.FromString,
                _registered_method=True)


class ConsoleServiceServicer(object):
    """ConsoleService provides safe, user-facing gateway summary methods.
    """

    def GetViewer(self, request, context):
        """GetViewer returns the authenticated user without credentials or tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsoleCapabilities(self, request, context):
        """GetConsoleCapabilities reports features available on this gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverview(self, request, context):
        """GetOverview returns an authorized summary for one workspace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsoleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetViewer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetViewer,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetViewerRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetViewerResponse.SerializeToString,
            ),
            'GetConsoleCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsoleCapabilities,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetConsoleCapabilitiesRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetConsoleCapabilitiesResponse.SerializeToString,
            ),
            'GetOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverview,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetOverviewRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetOverviewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cauteum.control.v1.ConsoleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cauteum.control.v1.ConsoleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsoleService(object):
    """ConsoleService provides safe, user-facing gateway summary methods.
    """

    @staticmethod
    def GetViewer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.ConsoleService/GetViewer',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetViewerRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetViewerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsoleCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.ConsoleService/GetConsoleCapabilities',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetConsoleCapabilitiesRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetConsoleCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.ConsoleService/GetOverview',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetOverviewRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetOverviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SandboxServiceStub(object):
    """SandboxService provides user-facing sandbox inventory methods.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSandboxes = channel.unary_unary(
                '/cauteum.control.v1.SandboxService/ListSandboxes',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxesRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxesResponse.FromString,
                _registered_method=True)
        self.GetSandbox = channel.unary_unary(
                '/cauteum.control.v1.SandboxService/GetSandbox',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxResponse.FromString,
                _registered_method=True)
        self.WatchSandboxes = channel.unary_stream(
                '/cauteum.control.v1.SandboxService/WatchSandboxes',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxesRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxesResponse.FromString,
                _registered_method=True)
        self.GetSandboxLogs = channel.unary_unary(
                '/cauteum.control.v1.SandboxService/GetSandboxLogs',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxLogsRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxLogsResponse.FromString,
                _registered_method=True)
        self.WatchSandboxLogs = channel.unary_stream(
                '/cauteum.control.v1.SandboxService/WatchSandboxLogs',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxLogsRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxLogsResponse.FromString,
                _registered_method=True)
        self.CreateSandbox = channel.unary_unary(
                '/cauteum.control.v1.SandboxService/CreateSandbox',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.CreateSandboxRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.CreateSandboxResponse.FromString,
                _registered_method=True)
        self.StartSandbox = channel.unary_unary(
                '/cauteum.control.v1.SandboxService/StartSandbox',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.StartSandboxRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.StartSandboxResponse.FromString,
                _registered_method=True)
        self.StopSandbox = channel.unary_unary(
                '/cauteum.control.v1.SandboxService/StopSandbox',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.StopSandboxRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.StopSandboxResponse.FromString,
                _registered_method=True)
        self.DeleteSandbox = channel.unary_unary(
                '/cauteum.control.v1.SandboxService/DeleteSandbox',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.DeleteSandboxRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.DeleteSandboxResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer(object):
    """SandboxService provides user-facing sandbox inventory methods.
    """

    def ListSandboxes(self, request, context):
        """ListSandboxes returns a bounded page of one workspace's sandbox records.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandbox(self, request, context):
        """GetSandbox returns one sandbox record visible to the caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSandboxes(self, request, context):
        """WatchSandboxes begins with a full reset/snapshot and then sends changes.
        Reconnect by opening a new stream and replacing the prior client state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandboxLogs(self, request, context):
        """GetSandboxLogs returns a bounded tail of one visible sandbox's log buffer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSandboxLogs(self, request, context):
        """WatchSandboxLogs starts with a tail and then follows new buffered lines.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSandbox(self, request, context):
        """These actions execute against the configured runtime, never the REST registry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSandboxes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSandboxes,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxesRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxesResponse.SerializeToString,
            ),
            'GetSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandbox,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxResponse.SerializeToString,
            ),
            'WatchSandboxes': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSandboxes,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxesRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxesResponse.SerializeToString,
            ),
            'GetSandboxLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandboxLogs,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxLogsRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxLogsResponse.SerializeToString,
            ),
            'WatchSandboxLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSandboxLogs,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxLogsRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxLogsResponse.SerializeToString,
            ),
            'CreateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandbox,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.CreateSandboxRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.CreateSandboxResponse.SerializeToString,
            ),
            'StartSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSandbox,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.StartSandboxRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.StartSandboxResponse.SerializeToString,
            ),
            'StopSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSandbox,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.StopSandboxRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.StopSandboxResponse.SerializeToString,
            ),
            'DeleteSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSandbox,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.DeleteSandboxRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.DeleteSandboxResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cauteum.control.v1.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cauteum.control.v1.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """SandboxService provides user-facing sandbox inventory methods.
    """

    @staticmethod
    def ListSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.SandboxService/ListSandboxes',
            cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxesRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.SandboxService/GetSandbox',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cauteum.control.v1.SandboxService/WatchSandboxes',
            cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxesRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandboxLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.SandboxService/GetSandboxLogs',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxLogsRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSandboxLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cauteum.control.v1.SandboxService/WatchSandboxLogs',
            cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxLogsRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.WatchSandboxLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.SandboxService/CreateSandbox',
            cauteum_dot_control_dot_v1_dot_console__pb2.CreateSandboxRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.CreateSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.SandboxService/StartSandbox',
            cauteum_dot_control_dot_v1_dot_console__pb2.StartSandboxRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.StartSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.SandboxService/StopSandbox',
            cauteum_dot_control_dot_v1_dot_console__pb2.StopSandboxRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.StopSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.SandboxService/DeleteSandbox',
            cauteum_dot_control_dot_v1_dot_console__pb2.DeleteSandboxRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.DeleteSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OperationsServiceStub(object):
    """OperationsService lets a user reconcile a mutation after a lost response.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOperation = channel.unary_unary(
                '/cauteum.control.v1.OperationsService/GetOperation',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetOperationResponse.FromString,
                _registered_method=True)
        self.ListOperations = channel.unary_unary(
                '/cauteum.control.v1.OperationsService/ListOperations',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListOperationsRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListOperationsResponse.FromString,
                _registered_method=True)
        self.ListAuditEvents = channel.unary_unary(
                '/cauteum.control.v1.OperationsService/ListAuditEvents',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListAuditEventsRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListAuditEventsResponse.FromString,
                _registered_method=True)


class OperationsServiceServicer(object):
    """OperationsService lets a user reconcile a mutation after a lost response.
    """

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuditEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetOperationRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetOperationResponse.SerializeToString,
            ),
            'ListOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOperations,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListOperationsRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListOperationsResponse.SerializeToString,
            ),
            'ListAuditEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuditEvents,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListAuditEventsRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListAuditEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cauteum.control.v1.OperationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cauteum.control.v1.OperationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperationsService(object):
    """OperationsService lets a user reconcile a mutation after a lost response.
    """

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.OperationsService/GetOperation',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetOperationRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.OperationsService/ListOperations',
            cauteum_dot_control_dot_v1_dot_console__pb2.ListOperationsRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.ListOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAuditEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.OperationsService/ListAuditEvents',
            cauteum_dot_control_dot_v1_dot_console__pb2.ListAuditEventsRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.ListAuditEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CatalogServiceStub(object):
    """CatalogService exposes workspace-visible service and workload metadata.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListServices = channel.unary_unary(
                '/cauteum.control.v1.CatalogService/ListServices',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListServicesRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListServicesResponse.FromString,
                _registered_method=True)
        self.ListTemplates = channel.unary_unary(
                '/cauteum.control.v1.CatalogService/ListTemplates',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListTemplatesRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListTemplatesResponse.FromString,
                _registered_method=True)
        self.ListWorkspaces = channel.unary_unary(
                '/cauteum.control.v1.CatalogService/ListWorkspaces',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListWorkspacesRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListWorkspacesResponse.FromString,
                _registered_method=True)
        self.GetWorkspace = channel.unary_unary(
                '/cauteum.control.v1.CatalogService/GetWorkspace',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetWorkspaceRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetWorkspaceResponse.FromString,
                _registered_method=True)


class CatalogServiceServicer(object):
    """CatalogService exposes workspace-visible service and workload metadata.
    """

    def ListServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkspaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServices,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListServicesRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListServicesResponse.SerializeToString,
            ),
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListTemplatesRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListTemplatesResponse.SerializeToString,
            ),
            'ListWorkspaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkspaces,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListWorkspacesRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListWorkspacesResponse.SerializeToString,
            ),
            'GetWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspace,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetWorkspaceRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetWorkspaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cauteum.control.v1.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cauteum.control.v1.CatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogService(object):
    """CatalogService exposes workspace-visible service and workload metadata.
    """

    @staticmethod
    def ListServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.CatalogService/ListServices',
            cauteum_dot_control_dot_v1_dot_console__pb2.ListServicesRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.ListServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.CatalogService/ListTemplates',
            cauteum_dot_control_dot_v1_dot_console__pb2.ListTemplatesRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.ListTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkspaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.CatalogService/ListWorkspaces',
            cauteum_dot_control_dot_v1_dot_console__pb2.ListWorkspacesRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.ListWorkspacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.CatalogService/GetWorkspace',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetWorkspaceRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PolicyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGlobalPolicy = channel.unary_unary(
                '/cauteum.control.v1.PolicyService/GetGlobalPolicy',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetGlobalPolicyRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetGlobalPolicyResponse.FromString,
                _registered_method=True)
        self.UpdateGlobalPolicy = channel.unary_unary(
                '/cauteum.control.v1.PolicyService/UpdateGlobalPolicy',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateGlobalPolicyRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateGlobalPolicyResponse.FromString,
                _registered_method=True)
        self.GetSandboxPolicy = channel.unary_unary(
                '/cauteum.control.v1.PolicyService/GetSandboxPolicy',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyResponse.FromString,
                _registered_method=True)
        self.UpdateSandboxPolicy = channel.unary_unary(
                '/cauteum.control.v1.PolicyService/UpdateSandboxPolicy',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateSandboxPolicyRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateSandboxPolicyResponse.FromString,
                _registered_method=True)
        self.ListSandboxPolicyRevisions = channel.unary_unary(
                '/cauteum.control.v1.PolicyService/ListSandboxPolicyRevisions',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxPolicyRevisionsRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxPolicyRevisionsResponse.FromString,
                _registered_method=True)
        self.GetSandboxPolicyRevision = channel.unary_unary(
                '/cauteum.control.v1.PolicyService/GetSandboxPolicyRevision',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyRevisionRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyRevisionResponse.FromString,
                _registered_method=True)
        self.ListPolicyProposals = channel.unary_unary(
                '/cauteum.control.v1.PolicyService/ListPolicyProposals',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListPolicyProposalsRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListPolicyProposalsResponse.FromString,
                _registered_method=True)
        self.GetPolicyProposal = channel.unary_unary(
                '/cauteum.control.v1.PolicyService/GetPolicyProposal',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetPolicyProposalRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetPolicyProposalResponse.FromString,
                _registered_method=True)
        self.ApprovePolicyProposal = channel.unary_unary(
                '/cauteum.control.v1.PolicyService/ApprovePolicyProposal',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ApprovePolicyProposalRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ApprovePolicyProposalResponse.FromString,
                _registered_method=True)
        self.RejectPolicyProposal = channel.unary_unary(
                '/cauteum.control.v1.PolicyService/RejectPolicyProposal',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.RejectPolicyProposalRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.RejectPolicyProposalResponse.FromString,
                _registered_method=True)


class PolicyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGlobalPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGlobalPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandboxPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSandboxPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSandboxPolicyRevisions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandboxPolicyRevision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicyProposals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicyProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApprovePolicyProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectPolicyProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGlobalPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalPolicy,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetGlobalPolicyRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetGlobalPolicyResponse.SerializeToString,
            ),
            'UpdateGlobalPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGlobalPolicy,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateGlobalPolicyRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateGlobalPolicyResponse.SerializeToString,
            ),
            'GetSandboxPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandboxPolicy,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyResponse.SerializeToString,
            ),
            'UpdateSandboxPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSandboxPolicy,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateSandboxPolicyRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateSandboxPolicyResponse.SerializeToString,
            ),
            'ListSandboxPolicyRevisions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSandboxPolicyRevisions,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxPolicyRevisionsRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxPolicyRevisionsResponse.SerializeToString,
            ),
            'GetSandboxPolicyRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandboxPolicyRevision,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyRevisionRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyRevisionResponse.SerializeToString,
            ),
            'ListPolicyProposals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicyProposals,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListPolicyProposalsRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListPolicyProposalsResponse.SerializeToString,
            ),
            'GetPolicyProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicyProposal,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetPolicyProposalRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetPolicyProposalResponse.SerializeToString,
            ),
            'ApprovePolicyProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.ApprovePolicyProposal,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ApprovePolicyProposalRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ApprovePolicyProposalResponse.SerializeToString,
            ),
            'RejectPolicyProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectPolicyProposal,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.RejectPolicyProposalRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.RejectPolicyProposalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cauteum.control.v1.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cauteum.control.v1.PolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGlobalPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.PolicyService/GetGlobalPolicy',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetGlobalPolicyRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetGlobalPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGlobalPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.PolicyService/UpdateGlobalPolicy',
            cauteum_dot_control_dot_v1_dot_console__pb2.UpdateGlobalPolicyRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.UpdateGlobalPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandboxPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.PolicyService/GetSandboxPolicy',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSandboxPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.PolicyService/UpdateSandboxPolicy',
            cauteum_dot_control_dot_v1_dot_console__pb2.UpdateSandboxPolicyRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.UpdateSandboxPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSandboxPolicyRevisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.PolicyService/ListSandboxPolicyRevisions',
            cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxPolicyRevisionsRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.ListSandboxPolicyRevisionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandboxPolicyRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.PolicyService/GetSandboxPolicyRevision',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyRevisionRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetSandboxPolicyRevisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicyProposals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.PolicyService/ListPolicyProposals',
            cauteum_dot_control_dot_v1_dot_console__pb2.ListPolicyProposalsRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.ListPolicyProposalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicyProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.PolicyService/GetPolicyProposal',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetPolicyProposalRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetPolicyProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApprovePolicyProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.PolicyService/ApprovePolicyProposal',
            cauteum_dot_control_dot_v1_dot_console__pb2.ApprovePolicyProposalRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.ApprovePolicyProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectPolicyProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.PolicyService/RejectPolicyProposal',
            cauteum_dot_control_dot_v1_dot_console__pb2.RejectPolicyProposalRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.RejectPolicyProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProviderProfileServiceStub(object):
    """ProviderProfileService preserves the full Cauteum profile document while
    keeping profile management inside the authenticated client API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProviderProfiles = channel.unary_unary(
                '/cauteum.control.v1.ProviderProfileService/ListProviderProfiles',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListProviderProfilesRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListProviderProfilesResponse.FromString,
                _registered_method=True)
        self.GetProviderProfile = channel.unary_unary(
                '/cauteum.control.v1.ProviderProfileService/GetProviderProfile',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetProviderProfileRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetProviderProfileResponse.FromString,
                _registered_method=True)
        self.ImportProviderProfile = channel.unary_unary(
                '/cauteum.control.v1.ProviderProfileService/ImportProviderProfile',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ImportProviderProfileRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ImportProviderProfileResponse.FromString,
                _registered_method=True)
        self.UpdateProviderProfile = channel.unary_unary(
                '/cauteum.control.v1.ProviderProfileService/UpdateProviderProfile',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderProfileRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderProfileResponse.FromString,
                _registered_method=True)
        self.DeleteProviderProfile = channel.unary_unary(
                '/cauteum.control.v1.ProviderProfileService/DeleteProviderProfile',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.DeleteProviderProfileRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.DeleteProviderProfileResponse.FromString,
                _registered_method=True)


class ProviderProfileServiceServicer(object):
    """ProviderProfileService preserves the full Cauteum profile document while
    keeping profile management inside the authenticated client API.
    """

    def ListProviderProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportProviderProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProviderProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProviderProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProviderProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviderProfiles,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListProviderProfilesRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ListProviderProfilesResponse.SerializeToString,
            ),
            'GetProviderProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderProfile,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetProviderProfileRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.GetProviderProfileResponse.SerializeToString,
            ),
            'ImportProviderProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportProviderProfile,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.ImportProviderProfileRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.ImportProviderProfileResponse.SerializeToString,
            ),
            'UpdateProviderProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProviderProfile,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderProfileRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderProfileResponse.SerializeToString,
            ),
            'DeleteProviderProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProviderProfile,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.DeleteProviderProfileRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.DeleteProviderProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cauteum.control.v1.ProviderProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cauteum.control.v1.ProviderProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProviderProfileService(object):
    """ProviderProfileService preserves the full Cauteum profile document while
    keeping profile management inside the authenticated client API.
    """

    @staticmethod
    def ListProviderProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.ProviderProfileService/ListProviderProfiles',
            cauteum_dot_control_dot_v1_dot_console__pb2.ListProviderProfilesRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.ListProviderProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.ProviderProfileService/GetProviderProfile',
            cauteum_dot_control_dot_v1_dot_console__pb2.GetProviderProfileRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.GetProviderProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportProviderProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.ProviderProfileService/ImportProviderProfile',
            cauteum_dot_control_dot_v1_dot_console__pb2.ImportProviderProfileRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.ImportProviderProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProviderProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.ProviderProfileService/UpdateProviderProfile',
            cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderProfileRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProviderProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.ProviderProfileService/DeleteProviderProfile',
            cauteum_dot_control_dot_v1_dot_console__pb2.DeleteProviderProfileRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.DeleteProviderProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProviderCredentialServiceStub(object):
    """ProviderCredentialService handles Cauteum-only secret patch semantics.
    OpenShell Provider.Update replaces the full credential map, so partial
    updates stay behind this narrow authenticated method.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateProviderCredentials = channel.unary_unary(
                '/cauteum.control.v1.ProviderCredentialService/UpdateProviderCredentials',
                request_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderCredentialsRequest.SerializeToString,
                response_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderCredentialsResponse.FromString,
                _registered_method=True)


class ProviderCredentialServiceServicer(object):
    """ProviderCredentialService handles Cauteum-only secret patch semantics.
    OpenShell Provider.Update replaces the full credential map, so partial
    updates stay behind this narrow authenticated method.
    """

    def UpdateProviderCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderCredentialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateProviderCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProviderCredentials,
                    request_deserializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderCredentialsRequest.FromString,
                    response_serializer=cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderCredentialsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cauteum.control.v1.ProviderCredentialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cauteum.control.v1.ProviderCredentialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProviderCredentialService(object):
    """ProviderCredentialService handles Cauteum-only secret patch semantics.
    OpenShell Provider.Update replaces the full credential map, so partial
    updates stay behind this narrow authenticated method.
    """

    @staticmethod
    def UpdateProviderCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cauteum.control.v1.ProviderCredentialService/UpdateProviderCredentials',
            cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderCredentialsRequest.SerializeToString,
            cauteum_dot_control_dot_v1_dot_console__pb2.UpdateProviderCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
